// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyX8YX1LKAnP3TOdaddz6yAX0hVIf0Acs',
    appId: '1:969668756665:web:55ff3f3734c7387f458768',
    messagingSenderId: '969668756665',
    projectId: 'quiz-app-4fd66',
    authDomain: 'quiz-app-4fd66.firebaseapp.com',
    storageBucket: 'quiz-app-4fd66.appspot.com',
    measurementId: 'G-PFDXKEQ8HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5ra7AMy_Fv9IDlZ2Kt8GOG0Fx1-TCmhs',
    appId: '1:969668756665:android:3013e23de08a13d5458768',
    messagingSenderId: '969668756665',
    projectId: 'quiz-app-4fd66',
    storageBucket: 'quiz-app-4fd66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhYcixNl0MOjwgwdbCIKwBEcRGfkmoh4I',
    appId: '1:969668756665:ios:4451afbd862fbdb8458768',
    messagingSenderId: '969668756665',
    projectId: 'quiz-app-4fd66',
    storageBucket: 'quiz-app-4fd66.appspot.com',
    androidClientId: '969668756665-0e2j8520orhit38igs2ejco08r4jn4o9.apps.googleusercontent.com',
    iosClientId: '969668756665-baafgb8akifljdcoa8ltcu1hb0mgfvp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhYcixNl0MOjwgwdbCIKwBEcRGfkmoh4I',
    appId: '1:969668756665:ios:4451afbd862fbdb8458768',
    messagingSenderId: '969668756665',
    projectId: 'quiz-app-4fd66',
    storageBucket: 'quiz-app-4fd66.appspot.com',
    androidClientId: '969668756665-0e2j8520orhit38igs2ejco08r4jn4o9.apps.googleusercontent.com',
    iosClientId: '969668756665-baafgb8akifljdcoa8ltcu1hb0mgfvp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyX8YX1LKAnP3TOdaddz6yAX0hVIf0Acs',
    appId: '1:969668756665:web:5022f1dbf5ea0aca458768',
    messagingSenderId: '969668756665',
    projectId: 'quiz-app-4fd66',
    authDomain: 'quiz-app-4fd66.firebaseapp.com',
    storageBucket: 'quiz-app-4fd66.appspot.com',
    measurementId: 'G-NEMPNWCH0G',
  );

}